import type { Metadata } from "next";
import { Raleway } from "next/font/google";

import "./globals.css";

import Footer from "../components/organisms/Footer";
import Navbar from "../components/organisms/Navbar";

import { DataProvider } from "@/context/data.context";
import ToastProvider from "@/context/toast.context";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Proyecto Hedy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <DataProvider>
          <ToastProvider>
            <Navbar />
            {children}
            <Footer />
          </ToastProvider>
        </DataProvider>
      </body>
    </html>
  );
}
